### ISSUE TITLE
& in url cause issue on windows

### ISSUE THREAD

**Issue by Lan-Hekary** [azhar22k/ourl#7]
**Describe the bug**
using & in URL cause issue on windows

**To Reproduce**
use this code :
`require('out-url').open('http://qrcode.kaywa.com/img.php?s=8&d=Hello');`
notice the `&` before `d=Hello` is not escaped it should be `^&` in windows as far as I know from this comment
https://stackoverflow.com/questions/8500326/how-to-use-nodejs-to-open-default-browser-and-navigate-to-a-specific-url#comment110363559_49013356

**Expected behavior**
to open without adding escape char for windows.

**Suggested**
process the URL and add escape chars if necessary.

**Desktop (please complete the following information):**
 - OS: windows
 - Version 1.1.1

**Comment by azhar22k** [comment]
Seems to be doable very easily, just need to URL parse the querystring
